{{- if and (default false (default dict .Values.networkPolicies).enabled) (default false (default dict .Values.monitoring).enabled) }}
# Allow Traffic to authservice
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-headlamp-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 9090
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: prometheus
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
{{- end }}
