{{- if and (default false (default dict .Values.istio).enabled) (default false (default dict .Values.istio.hardened).enabled) -}}
{{- $dot := . }}
{{- range .Values.istio.headlamp.gateways -}}
{{- $gatewayParts := split "/" . }}
{{- $namespace := $gatewayParts._0 }}
{{- $name := $gatewayParts._1 }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ $name }}-ingress-gateway-authz-policy
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "headlamp.selectorLabels" $dot | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
        principals:
        - "cluster.local/ns/{{ $namespace }}/sa/{{ $name }}-ingress-gateway-service-account"
---
{{ end -}}
{{- end }}
