{{- /* Render Istio Auth policies */ -}}
{{- if and (default false .Values.istio.enabled) (default false .Values.istio.hardened.enabled) -}}
{{- range $.Values.istio.hardened.customAuthorizationPolicies -}}
{{- if .enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}

spec:
  {{- toYaml .spec | nindent 2 }}
---
{{ end -}}
{{ end -}}
{{- end -}}
