{{- if and .Values.monitoring.enabled .Values.metrics.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: headlamp-exporter-service-monitor
  namespace: {{ .Release.Namespace }}
spec:
  jobLabel: {{ .Release.Name }}
  endpoints:
    - interval: 30s
      port: http
      path: "/probe"
      params:
        module:
          - http_2xx
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - targetLabel: __address__
          replacement: {{ .Release.Name }}-metrics.{{ .Release.Namespace }}.svc:9115
        - sourceLabels: [__param_target]
          targetLabel: instance
      {{- if .Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml .Values.monitoring.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
