{{- if and (default false .Values.istio.enabled) (default false .Values.istio.hardened.enabled) -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.istio.headlamp.labels }}
{{ toYaml .Values.istio.headlamp.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.headlamp.annotations }}
  annotations:
{{ toYaml .Values.istio.headlamp.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.headlamp.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.headlamp.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
        - destination:
            port:
              number: 80
            host: {{ template "headlamp.fullname" . }}
{{- end }}
