{{- if and (.Values.istio.enabled) (.Values.istio.headlamp.enabled) -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: headlamp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: headlamp
  {{- if .Values.istio.headlamp.labels }}
{{ toYaml .Values.istio.headlamp.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.headlamp.annotations }}
  annotations:
{{ toYaml .Values.istio.headlamp.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.headlamp.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.headlamp.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
