{{- /* Render Istio Sidecar */ -}}
{{- if and (default false .Values.istio.enabled) (default false .Values.istio.hardened.enabled) -}}
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: {{ .Release.Name }}-sidecar
  namespace: {{.Release.Namespace}}
  labels:
    name: {{ template "headlamp.name" . }}
spec:
  outboundTrafficPolicy:
    mode: {{ .Values.istio.hardened.outboundTrafficPolicyMode }}
{{- end }}
