{{- /* Render Istio ServiceEntries */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.config.oidc.clientID -}}
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-sso-headlamp
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ include "sso.host" $ }}
  location: MESH_EXTERNAL
  exportTo: 
  - "*"
  ports:
    - number: 443
      protocol: TLS
      name: https
  resolution: DNS
---
{{- end -}}

